### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by jwylie01** [esologic/blinkbox#1]
This is great! I use lots of addressable LEDS and this will really make testing them easier. I’m thinking about possibly adding a voltage reducer to your design so I can use a 12V power supply and test both 12V and 5V lights. I’m not that good with Fusion or other cad programs so modifying the case to have a 5V and 12V out connection is going to be tricky for me.

**Comment by esologic** [comment]
I work on commission! Send me an email if you're interested in having me make something for you dev(at)esologic.com
